### ISSUE TITLE
Consistent notation for mutation names in watchlist .vcf files

### ISSUE THREAD

**Issue by dfornika** [jts/ncov-watch#4]
There are some inconsistencies in the notation that is used for mutation names in the watchlists (eg. `S_` vs `S:`):

https://github.com/jts/ncov-watch/blob/429cc44719b19cc5c1726ef7546e5941c82706a1/ncov_watch/watchlists/sa_variant.vcf#L15

https://github.com/jts/ncov-watch/blob/429cc44719b19cc5c1726ef7546e5941c82706a1/ncov_watch/watchlists/uk_variant.vcf#L22

https://github.com/jts/ncov-watch/blob/429cc44719b19cc5c1726ef7546e5941c82706a1/ncov_watch/watchlists/spike_mutations.vcf#L13

Could they be standardized to use the same notation?

**Comment by jts** [comment]
Thanks for pointing that out, fixed.
